// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_fgqf9PeGWRqajjs9PMZJDTTwg8i8x7Y',
    appId: '1:155290193485:web:07da2aa83a7df2e1d7d604',
    messagingSenderId: '155290193485',
    projectId: 'todo-app-c940e',
    authDomain: 'todo-app-c940e.firebaseapp.com',
    storageBucket: 'todo-app-c940e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdtb1jQoi79BRlglT71yoWK7osHTmJZM',
    appId: '1:155290193485:android:eb9b35a46f155a5cd7d604',
    messagingSenderId: '155290193485',
    projectId: 'todo-app-c940e',
    storageBucket: 'todo-app-c940e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnrnVB9tvpIj_3sIJZAi0En9-i32kIzY',
    appId: '1:155290193485:ios:0e953e4d266be167d7d604',
    messagingSenderId: '155290193485',
    projectId: 'todo-app-c940e',
    storageBucket: 'todo-app-c940e.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnrnVB9tvpIj_3sIJZAi0En9-i32kIzY',
    appId: '1:155290193485:ios:0e953e4d266be167d7d604',
    messagingSenderId: '155290193485',
    projectId: 'todo-app-c940e',
    storageBucket: 'todo-app-c940e.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_fgqf9PeGWRqajjs9PMZJDTTwg8i8x7Y',
    appId: '1:155290193485:web:6620ef429c8311ddd7d604',
    messagingSenderId: '155290193485',
    projectId: 'todo-app-c940e',
    authDomain: 'todo-app-c940e.firebaseapp.com',
    storageBucket: 'todo-app-c940e.firebasestorage.app',
  );
}
